create table borrowers (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    email varchar(320) not null,
    row_version bigint not null default 0,
    created_at timestamp with time zone not null
);

create unique index uk_borrowers_email on borrowers (email);

create table book_catalog_entries (
    id bigint generated by default as identity primary key,
    isbn varchar(20) not null,
    title varchar(255) not null,
    author varchar(255) not null,
    row_version bigint not null default 0,
    created_at timestamp with time zone not null
);

create unique index uk_book_catalog_entries_isbn on book_catalog_entries (isbn);
create index idx_book_catalog_entries_title on book_catalog_entries (title);

create table books (
    id bigint generated by default as identity primary key,
    catalog_entry_id bigint not null,
    row_version bigint not null default 0,
    created_at timestamp with time zone not null,
    constraint fk_books_catalog_entry foreign key (catalog_entry_id) references book_catalog_entries (id)
);

create index idx_books_catalog_entry on books (catalog_entry_id);

create table loans (
    id bigint generated by default as identity primary key,
    borrower_id bigint not null,
    book_id bigint not null,
    borrowed_at timestamp with time zone not null,
    returned_at timestamp with time zone,
    active_loan_book_id bigint,
    row_version bigint not null default 0,
    constraint chk_loans_active_loan_book_id check (
        (returned_at is null and active_loan_book_id = book_id)
        or (returned_at is not null and active_loan_book_id is null)
    ),
    constraint fk_loans_borrower foreign key (borrower_id) references borrowers (id),
    constraint fk_loans_book foreign key (book_id) references books (id)
);

create index idx_loans_book_active on loans (book_id, returned_at);
create index idx_loans_borrower_active on loans (borrower_id, returned_at);
create unique index uk_loans_active_loan_book_id on loans (active_loan_book_id);
